### ISSUE TITLE
Query -> Request issue

### ISSUE THREAD

**Issue by artificial-jamesirei** [LastAbyss/SimpleGraphQL-For-Unity#21]
Hello!  I'm trying to use this package to make graphql requests but when I try to follow the example code to send a request, it throws an error about it can't convert a query to a request.  I would appreciate some guidance on this, thank you!

**Comment by johanhelsing** [comment]
The example is outdated. You can make a request from a query by calling

    query.ToRequest()

You could also create a request directly. The easiest thing is probably take a look at the tests for inspiration until we've fixed the examples.

Thanks for pointing it out!

**Comment by johanhelsing** [comment]
I made some quick  edits to the readme. Let us know if it works and is clear enough :)

**Comment by artificial-jamesirei** [comment]
@johanhelsing That was it, thank you!
