### ISSUE TITLE
GraphQLConfig Files list doesn't accept .graphql files

### ISSUE THREAD

**Issue by skjalgsm** [LastAbyss/SimpleGraphQL-For-Unity#22]
I have a bunch of graphql files I'd like to use, but I cant drag them into the Files field in the GraphQLConfig.

When looking at the code, those files are actually ScriptableObjects which I can't create as they lack the appropriate menu item for it. How do I proceed?

**Comment by NavidK0** [comment]
Hi there! SimpleGraphQL contains a scripted importer that should automatically register the graphql files as a scriptable object type.

Are there any errors in console? Have you tried reimporting the graphql files? Double check the extension too (.graphql). The import code is located in Editor, but I believe nothing should've changed within the last few versions that would've broken it.

**Comment by skjalgsm** [comment]
Wow, I'm an idiot. I stored them as .qraphql files

**Comment by NavidK0** [comment]
Ahh no worries, happens to the best of us 😅

**Comment by skjalgsm** [comment]
Haha yes, thank you for pointing me in the right direction :)

tir. 13. jul. 2021 kl. 13:47 skrev Navid Kabir ***@***.***>:
