### ISSUE TITLE
Assembly with name 'Tests' already exists (Packages/com.lastabyss.simplegraphql/Tests/Runtime/LastAbyss.SimpleGraphQL.Runtime.Tests.asmdef)

### ISSUE THREAD

**Issue by skjalgsm** [LastAbyss/SimpleGraphQL-For-Unity#25]
The Runtime Tests asmdefs name is just Tests instead of `LastAbyss.SimpleGraphQL.Runtime.Tests`

![image](https://user-images.githubusercontent.com/568589/125537121-128be394-634a-48ed-928e-85b0908f0fd8.png)

**Comment by NavidK0** [comment]
Good catch, thanks! Resolved with ec9150d5115650cc6c5755885b222df9ceba810c.
