### ISSUE TITLE
Wrong URL in the documentation

### ISSUE THREAD

**Issue by Inatigerdream** [LastAbyss/SimpleGraphQL-For-Unity#32]
git url didn't work for me. This one did: https://github.com/LastAbyss/SimpleGraphQL-For-Unity.git

**Comment by NavidK0** [comment]
Erm, am I mistaken, or is that the same URL as in the documentation?

![](https://i.imgur.com/bWypc98.png)

**Comment by Inatigerdream** [comment]
weird my bad i guess
