### ISSUE TITLE
Subscriptions didn't work with my GraphQL Server until I added an empty Payload to the connection init.

### ISSUE THREAD

**Issue by mkuhr** [LastAbyss/SimpleGraphQL-For-Unity#33]

**Comment by NavidK0** [comment]
What server are you using? Is this standard protocol?

**Comment by mkuhr** [comment]
it was https://dgraph.io/ and same behaviour on the selfhosted one in docker. 
I dont know about subscription ws protocoll standards. had to find out why it wasnt working using wireshark and graphiql.

The difference is in my title. Your Plugin didnt send the empty payload and all graphiql did.

This plugin rocks. Thanks for it

**Comment by NavidK0** [comment]
> it was https://dgraph.io/ and same behaviour on the selfhosted one in docker.
> I dont know about subscription ws protocoll standards. had to find out why it wasnt working using wireshark and graphiql.
> 
> The difference is in my title. Your Plugin didnt send the empty payload and all graphiql did.
> 
> This plugin rocks. Thanks for it

I asked because I'm not sure about the subscription WS protocol standards either. 😅
Thanks for the additional information! It helps a lot. It seems like a bug on our end, so we can get it fixed.

This change probably shouldn't affect any other kinds of graphql servers either.
