### ISSUE TITLE
Headers not working in subscriptions with aws appsync

### ISSUE THREAD

**Issue by patdied** [LastAbyss/SimpleGraphQL-For-Unity#36]
Hello,

Nice work on the graphql queries and mutations.

Everything seems very easy to understand

I noticed when I add a header dictionary to the field to Subscribe like so:

bool success = await graphQL.Subscribe(
        query.ToRequest(),
        new Dictionary<string, string>
        {
            {"header", "headerSerializedCorrectly"},
            {"payload", "e30="},
        }
    );

The response from the server is the header and payload fields are missing in the header.

I followed the structure of AppSync to the Tee: https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html

**Comment by NavidK0** [comment]
Hey, sorry, I am unfamiliar with AWS AppSync, but I know one of the forks for this library hacked in AWS support.

Feel free to check it out, it may help you out more than I can:
https://github.com/lukeunbnd/SimpleGraphQL-For-Unity

**Comment by ghost** [comment]
Hey that's me! yeah it's not the greatest implementation of the AppSync Headers, But it should work. Let me know of any issues and I can look at fixing them. Is this something I should put a tad more effort into and merge back in here?

Note: I believe I also fixed a possible issue with subscriptions, it was breaking out instead of continuing.

**Comment by NavidK0** [comment]
@lukeunbnd Heya! Sorry to pull up your fork out of nowhere, but I do keep up with them every now and then!

It's entirely up to you if you want to clean it up and merge it into master. I'm not actively adding features or anything, so it'll be a welcome addition if you decide to.

**Comment by patdied** [comment]
Oh my goodness! It worked beautifully. You guys don't know how many different assets and other repos I've tried which all failed with subscriptions to appsync. I am not an expert with appsync and graphQL so it was a struggle to figure out why things weren't working. Thanks a lot!

**Comment by ghost** [comment]
> @lukeunbnd Heya! Sorry to pull up your fork out of nowhere, but I do keep up with them every now and then!
> 
> It's entirely up to you if you want to clean it up and merge it into master. I'm not actively adding features or anything, so it'll be a welcome addition if you decide to.

no problem, it's why GitHub is how it is! Thank you for putting in all the initial work.

Awesome, there are a few other things I want to add anyway as helper features. Might do that at a later point. 

@patdied glad it helped :)

**Comment by patdied** [comment]
A bit unrelated but I noticed if I have multiple subscriptions, all the RegisteredListener functions get called when either of them gets a response from the aws server.
