### ISSUE TITLE
definition for 'Result' and no accessible extension method 'Result' accepting a first argument of type 'Response<<anonymous type:

### ISSUE THREAD

**Issue by zkMyst** [LastAbyss/SimpleGraphQL-For-Unity#45]
Hi !
I'm trying to make a simple graphql query, supposed to return an array of integers. I've replaced my query and the value in the example. Nevertheless i'm getting the following error when trying to access `response.Result` :

`Response<<anonymous type: <anonymous type: string tokenId>[] tokens>>' does not contain a definition for 'Result' and no accessible extension method 'Result' accepting a first argument of type 'Response<<anonymous type: <anonymous type: string tokenId>[] tokens>>' could be found (are you missing a using directive or an assembly reference?)`

The return from the query is `{ owner: { tokens: Array<{ tokenID }> } }`

<img width="1122" alt="Screenshot 2022-12-31 at 13 59 30" src="https://user-images.githubusercontent.com/77244555/210139212-5a2e886b-e6f6-462e-9d95-577d9dc3778d.png">

The query is supposed to return an array of integers, is it giving me that error because of the return type?

Thanks a lot <3

**Comment by zkMyst** [comment]
Actually if I just copy paste the example I do get the same error:

<img width="813" alt="Screenshot 2022-12-31 at 14 32 34" src="https://user-images.githubusercontent.com/77244555/210140255-260da0ef-1747-4f4d-b57f-467dd964bc86.png">


`'Response<<anonymous type: <anonymous type: string name> continent>>' does not contain a definition for 'Result' and no accessible extension method 'Result' accepting a first argument of type 'Response<<anonymous type: <anonymous type: string name> continent>>' could be found (are you missing a using directive or an assembly reference?)`

**Comment by NavidK0** [comment]
(I saw your email, but I'll respond here to keep everything in one place.)

So the documentation is slightly wrong here, since `await client.Send()` will automatically unwrap the Task object for you. So you don't actually need `Result` if you do `await`. If you remove the `await`, the Result object will appear.

However, I recommend simply doing `response.Data.continent.name` since you are using async code.

I've gone ahead and updated the documentation as well.

**Comment by zkMyst** [comment]
Thanks a lot! I've removed `Result` from the path and it worked.

If the return from the query is supposed to be 

`{ owner: { tokens: Array<{ tokenID }> } }`

, is the `responseType` supposed to be 

`var responseType = new { owner = new { tokens = new { tokenID = "" } } };` ?

It's returning `null` with my current query setup: 

<img width="1138" alt="Screenshot 2022-12-31 at 17 31 26" src="https://user-images.githubusercontent.com/77244555/210151336-1a8b3c66-4cd7-40d0-aeb3-ed778630c218.png">

**Comment by NavidK0** [comment]
Tokens should be an array in your responseType if that's what you expect.

Something like (Sorry, I didn't test the following code out, but you get the gist):
```cs
var responseType = new { owner = new { tokens = new[] { tokenID = "" } } };
```

If you'd prefer, you can also make a class that contains the exact data structure you want and pass that in as a generic type parameter instead.
```cs
[Serializable]
public class GetTokensForOwnerResponse
{
    public Owner owner;

    [Serializable]
    public class Owner
    {
        public Token[] tokens;

        [Serialiable]
        public class Token
        {
            public string tokenID;
        }
    }
}

...
var response = await client.Send<GetTokensForOwnerResponse>(request);
Debug.Log(response.Data);
```

**Comment by zkMyst** [comment]
Edit: found the issue, i didn't add `($id: ID!)` to the query in the beggining : ) thanks for your help!

**Comment by NavidK0** [comment]
No problem! Closing as solved.
