### ISSUE TITLE
Doesn't build on Unity 2019.4

### ISSUE THREAD

**Issue by johanhelsing** [LastAbyss/SimpleGraphQL-For-Unity#9]
Complains about ScriptedImporter is missing.

Sorry, upgraded the repo to 2020.3 (where it builds fine) already, so I don't have the full error, just thought I'd flag it.

**Comment by NavidK0** [comment]
Should be fixed with 20cc1ea4d559ee1514ad4371ee7df0ab4571bf0d.

2020.2 took the Asset Importer stuff out of experimental, so the namespaces changed.
